### ISSUE TITLE
[Proposal] Migrate exercisebuilder tags to regexes

### ISSUE THREAD

**Issue by nygrenh** [testmycode/tmc-langs#13]
One problem with the current system is that tags with missing whitespace are not matched.

For example, `// BEGIN SOLUTION` is now getting matched whereas `//BEGIN SOLUTION` is not.

This was recently a problem in the C Programming course material.

**Comment by mpartel** [comment]
See https://github.com/testmycode/tmc-server/blob/master/lib/course_refresher/line_comment_based_filter.rb for the current regexes.
Since tmc-langs is supposed to replace that piece of code, either it should work identically or we should carefully verify all existing exercises against the new behaviour.

**Comment by nygrenh** [comment]
Judging from the code, it looks like every language has their own style for tags. That's likely a major issue in Langs.

**Comment by mpartel** [comment]
I think the `LineCommentBasedFilter` and `BlockCommentBasedFilter` superclasses were a fairly successful design choice.

**Comment by jamox** [comment]
+1 for the regex

**Comment by ljleppan** [comment]
Migrating this issue to #25 so that the Legacy course gets a better idea of what to do.
